apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: dev
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: myapp.local
      http:
        paths:
          # Frontend (default)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /customers(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: customer
                port:
                  number: 8001

          # API Gateway
          # - path: /api
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: api-gateway
          #       port:
          #         number: 8080

          # Products microservice (optional direct access)
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: products
                port:
                  number: 8002
        
